// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCuQYZGIPwcLAdGyEDrc2p3Ozc7iARe8',
    appId: '1:524047979416:web:42179831d6f2bfdec611ed',
    messagingSenderId: '524047979416',
    projectId: 'realtime-chat-app-72d15',
    authDomain: 'realtime-chat-app-72d15.firebaseapp.com',
    storageBucket: 'realtime-chat-app-72d15.firebasestorage.app',
    measurementId: 'G-9WSRC06J91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW916OVVFqHn4_AZB0eW7l87Y1QrgaEXo',
    appId: '1:524047979416:android:ce308ea23733b4bac611ed',
    messagingSenderId: '524047979416',
    projectId: 'realtime-chat-app-72d15',
    storageBucket: 'realtime-chat-app-72d15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvsVUG5Yxm2ZV4slpfZr1rP4w8epoc0M',
    appId: '1:524047979416:ios:6170eed452c13dabc611ed',
    messagingSenderId: '524047979416',
    projectId: 'realtime-chat-app-72d15',
    storageBucket: 'realtime-chat-app-72d15.firebasestorage.app',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkvsVUG5Yxm2ZV4slpfZr1rP4w8epoc0M',
    appId: '1:524047979416:ios:6170eed452c13dabc611ed',
    messagingSenderId: '524047979416',
    projectId: 'realtime-chat-app-72d15',
    storageBucket: 'realtime-chat-app-72d15.firebasestorage.app',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGCuQYZGIPwcLAdGyEDrc2p3Ozc7iARe8',
    appId: '1:524047979416:web:8fe96576a95a6aa1c611ed',
    messagingSenderId: '524047979416',
    projectId: 'realtime-chat-app-72d15',
    authDomain: 'realtime-chat-app-72d15.firebaseapp.com',
    storageBucket: 'realtime-chat-app-72d15.firebasestorage.app',
    measurementId: 'G-KPS221PZC9',
  );
}
